config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }

  root "pages#splash"

  resources :users, only: [:show]
  resources :categories do
    resources :transactions, only: [:index, :new, :create]
  end
  # Other application routes...

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :transactions
  belongs_to :user

  def total_amount
    transactions.sum(:amount)
  end

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :transactions
  has_and_belongs_to_many :users
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :category

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions
  has_many :categories
  has_many :groups

  validates :full_name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category created successfully!'
    else
      render :new
    end
  end

  # ...

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def splash
    # No need to define anything here, as this action is just for rendering the splash page
  end
end

app/controllers/registrations_controller.rb
# app/controllers/registrations_controller.rb

class RegistrationsController < Devise::RegistrationsController
  def after_sign_up_path_for(_resource)
    flash[:notice] = "Thank you for signing up! You've been redirected to the categories page."
    categories_path
  end

  def sign_up_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb

class SessionsController < Devise::SessionsController
  def after_sign_in_path_for(_resource)
    flash[:notice] = "Welcome back! You've been redirected to the categories page."
    categories_path
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category

  def index
    @transactions = @category.transactions.order(created_at: :desc)
  end

  def new
    @transaction = Transaction.new
    @categories = current_user.categories
  end

  def create
    @transaction = current_user.transactions.new(transaction_params)
    @transaction.category = @category

    if @transaction.save
      redirect_to category_transactions_path(@category), notice: 'Transaction created successfully!'
    else
      @categories = current_user.categories
      render :new
    end
  end

  private

  def set_category
    @category = current_user.categories.find(params[:category_id])
  end

  def transaction_params
    params.require(:transaction).permit(:name, :amount, category_ids: []) # Permit category_ids as an array
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  private

  def user_params
    params.require(:user).permit(:full_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<!-- app/views/categories/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Your Page Title</title>
  <!-- Add the Font Awesome link here -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
 
</head>
<body>
  <%= render partial: 'layouts/header' %>
   
    <% @categories.each do |category| %>
      <%= link_to category_transactions_path(category), class: "category-link" do %>
        <div class="category">
          <div class='icon-div'>
            <% if category.icon.present? %>
              <%= image_tag category.icon %>
            <% else %>
              <span class="no-icon-placeholder">No icon available</span>
            <% end %>
          </div>
          <div class="namount">
            <h3><%= category.name %></h3>
            <div class="date"><%= category.created_at.strftime('%d-%b-%Y') %></div>
          </div>
          <p>$<%= category.total_amount %></p>
        </div>
      <% end %>
    <% end %>    
  </div>
  <div class="user-name">  
  </div>
  <footer class="cat-p"><%= link_to 'Add Category', new_category_path %></p>  
</body>
</html>

app/views/categories/new.html.erb
<%= render partial: 'layouts/header' %>

<h2 class="cat-h2">Create a New Category</h2>

<%= form_with(model: @category, url: categories_path, local: true) do |form| %>
  <div class="cat-name">
    <%= form.text_field :name, placeholder: 'Category Name' %>
  </div>

  <div class="cat-icon">
    <%= form.text_field :icon, placeholder: 'Icon' %>
  </div>

  <div class="cat-sub">
    <%= form.submit "Save Category" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <div class="user-menu">
    <div class="sinout">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger signout-btn" %>
    </div>
    <div class="menu-items">
      <div class="left">
      <i class="fas fa-bars custom-icon" style="color: white;"></i> <!-- Hamburger icon -->
      </div>
      <div class="middle">
        <p class='big-title'><%= controller_name.titleize %></p> <!-- Category -->
      </div>
      <div class="right">
      <i class="fas fa-search custom-icon" style="color: white;"></i> <!-- Search icon -->
      </div>
    </div>
  </div>
<% else %>
  <div class="user-menu">
    <div class="middle">
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    </div>
  </div> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'splash', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'categories', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'transactions', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget_app</title>  
  <%= stylesheet_link_tag 'splash', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap">
</head>
<body>
  <div class="container">
    <h1>My Budget App</h1> 
    <div class="enter">
      <%= link_to 'SIGN UP', new_user_registration_path, class: "sign-up-link" %>
      <%= link_to 'LOG IN', new_user_session_path, class: "sign-in-link" %>
    </div>
  </div>
</body>
</html>

app/views/transactions/index.html.erb
<!-- app/views/transactions/index.html.erb -->
<div class="t-head">
  <h2>Transactions for <%= @category.name %></h2>
  <p class="bck"><%= link_to raw('&#8592;'), categories_path, class: "bck-link" %></p>
</div>
<p>Total Amount: $<%= @category.total_amount %></p>
<% @transactions.each do |transaction| %>
  <div class="transaction">
    <h3><%= transaction.name %></h3>
    <p>Amount: $<%= transaction.amount %></p>
  </div>
<% end %>
<p class="add-trans">
  <%= link_to 'Add Transaction', new_category_transaction_path(@category) %>
</p>

app/views/transactions/new.html.erb
<!-- app/views/transactions/new.html.erb -->

<h2 class="trans-h2">Create a New Transaction</h2>

<%= form_with(model: @transaction, url: category_transactions_path(@category), local: true) do |form| %>
  <div class="trans-name">
    <%= form.text_field :name, placeholder: 'Transaction Name' %>
  </div>

  <div class="trans-amt">
    <%= form.number_field :amount, placeholder: 'Amount' %>
  </div>

  <div class="trans-cat">
    <%= form.collection_select :category_id, @categories, :id, :name, placeholder: 'Select a Category' %>
  </div>

  <div class="trans-sub">
    <%= form.submit "Save Transaction" %>
  </div>
<% end %>

<% if @transaction.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
    <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>